#!/bin/bash

MARKDOWN_FILE=$1

PDF_FILE=$(basename $MARKDOWN_FILE .md).pdf

pandoc $MARKDOWN_FILE \
	--standalone \
	--template eisvogel \
	--listings \
	--variable listings-disable-line-numbers=true \
	--variable code-block-font-size=\\footnotesize \
	--variable table-use-row-colors=true \
	--variable geometry:margin=1in \
	--variable linkcolor=blue \
	--output $PDF_FILE

exit

	--variable header-includes:'\usepackage[export]{adjustbox} \let\includegraphicsbak\includegraphics \renewcommand*{\includegraphics}[2][]{\includegraphicsbak[frame,#1]{#2}}' \

# LaTeX font sizes:
# 
# Command             10pt    11pt    12pt
# \tiny               5       6       6
# \scriptsize         7       8       8
# \footnotesize       8       9       10
# \small              9       10      10.95
# \normalsize         10      10.95   12
# \large              12      12      14.4
# \Large              14.4    14.4    17.28
# \LARGE              17.28   17.28   20.74
# \huge               20.74   20.74   24.88
# \Huge               24.88   24.88   24.88
